development:
  facebook_key: "826643820685975"
  facebook_secret: "a836718c60a360b5c52ef2cf0b5f4fca"

  twitter_key: "NB4qEM6mFsomiOI26Sp8BQ"
  twitter_secret: "bTSpDvixWSpiYyZ5HaEp2KJYZsggKL7DnDZGbh7r8"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "1041392525048"
  google_secret: "jafjShTZP3ptYIZwMC7Iz4kR"

production:
  facebook_key: "826643820685975"
  facebook_secret: "a836718c60a360b5c52ef2cf0b5f4fca"

  twitter_key: "NB4qEM6mFsomiOI26Sp8BQ"
  twitter_secret: "bTSpDvixWSpiYyZ5HaEp2KJYZsggKL7DnDZGbh7r8"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"
